//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.11 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2017.09.06 at 01:34:55 AM CEST 
//


package pl.oskarpolak.automatic.models.soap.basicservice;

import javax.xml.bind.annotation.XmlEnum;
import javax.xml.bind.annotation.XmlEnumValue;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for alarmTypeType.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * <p>
 * <pre>
 * &lt;simpleType name="alarmTypeType"&gt;
 *   &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string"&gt;
 *     &lt;enumeration value="SERVICE-CALL"/&gt;
 *     &lt;enumeration value="HOME-CALL"/&gt;
 *     &lt;enumeration value="EVENT-CALL"/&gt;
 *     &lt;enumeration value="EDW-ALARM"/&gt;
 *     &lt;enumeration value="ECU-ALARM"/&gt;
 *     &lt;enumeration value="DISPOPILOT-OVERFLOW"/&gt;
 *     &lt;enumeration value="AREA-ENTRY"/&gt;
 *     &lt;enumeration value="AREA-EXIT"/&gt;
 *   &lt;/restriction&gt;
 * &lt;/simpleType&gt;
 * </pre>
 * 
 */
@XmlType(name = "alarmTypeType")
@XmlEnum
public enum AlarmTypeType {

    @XmlEnumValue("SERVICE-CALL")
    SERVICE_CALL("SERVICE-CALL"),
    @XmlEnumValue("HOME-CALL")
    HOME_CALL("HOME-CALL"),
    @XmlEnumValue("EVENT-CALL")
    EVENT_CALL("EVENT-CALL"),
    @XmlEnumValue("EDW-ALARM")
    EDW_ALARM("EDW-ALARM"),
    @XmlEnumValue("ECU-ALARM")
    ECU_ALARM("ECU-ALARM"),
    @XmlEnumValue("DISPOPILOT-OVERFLOW")
    DISPOPILOT_OVERFLOW("DISPOPILOT-OVERFLOW"),
    @XmlEnumValue("AREA-ENTRY")
    AREA_ENTRY("AREA-ENTRY"),
    @XmlEnumValue("AREA-EXIT")
    AREA_EXIT("AREA-EXIT");
    private final String value;

    AlarmTypeType(String v) {
        value = v;
    }

    public String value() {
        return value;
    }

    public static AlarmTypeType fromValue(String v) {
        for (AlarmTypeType c: AlarmTypeType.values()) {
            if (c.value.equals(v)) {
                return c;
            }
        }
        throw new IllegalArgumentException(v);
    }

}
