//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.11 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2017.09.06 at 01:34:55 AM CEST 
//


package pl.oskarpolak.automatic.models.soap.basicservice;

import java.math.BigInteger;
import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for anonymous complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType&gt;
 *   &lt;complexContent&gt;
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
 *       &lt;sequence&gt;
 *         &lt;element name="FLEETID" type="{http://www.fleetboard.com/data}fleetidType"/&gt;
 *         &lt;element name="FLEETNAME" type="{http://www.w3.org/2001/XMLSchema}string"/&gt;
 *         &lt;element name="FLEETINFORMATION"&gt;
 *           &lt;complexType&gt;
 *             &lt;complexContent&gt;
 *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
 *                 &lt;sequence&gt;
 *                   &lt;element name="STREET" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/&gt;
 *                   &lt;element name="POSTALCODE" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/&gt;
 *                   &lt;element name="CITY" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/&gt;
 *                   &lt;element name="COUNTRY" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/&gt;
 *                   &lt;element name="COUNTRYCODE" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/&gt;
 *                   &lt;element name="REGION" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/&gt;
 *                   &lt;element name="REGIONCODE" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/&gt;
 *                   &lt;element name="PAGEHEADING" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/&gt;
 *                   &lt;element name="FLEETTIMEZONE" type="{http://www.w3.org/2001/XMLSchema}integer" minOccurs="0"/&gt;
 *                   &lt;element name="FLEETTIMEZONEID" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/&gt;
 *                   &lt;element name="DLSAVING" type="{http://www.w3.org/2001/XMLSchema}integer" minOccurs="0"/&gt;
 *                   &lt;element name="DELTAETAMON" type="{http://www.w3.org/2001/XMLSchema}integer" minOccurs="0"/&gt;
 *                   &lt;element name="DELTAAREAMON" type="{http://www.w3.org/2001/XMLSchema}integer" minOccurs="0"/&gt;
 *                 &lt;/sequence&gt;
 *               &lt;/restriction&gt;
 *             &lt;/complexContent&gt;
 *           &lt;/complexType&gt;
 *         &lt;/element&gt;
 *         &lt;element name="FLEETRIGHTS"&gt;
 *           &lt;complexType&gt;
 *             &lt;complexContent&gt;
 *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
 *                 &lt;sequence&gt;
 *                   &lt;element ref="{http://www.fleetboard.com/data}RIGHT" maxOccurs="unbounded" minOccurs="0"/&gt;
 *                 &lt;/sequence&gt;
 *               &lt;/restriction&gt;
 *             &lt;/complexContent&gt;
 *           &lt;/complexType&gt;
 *         &lt;/element&gt;
 *         &lt;element name="FLEETPROPERTIES"&gt;
 *           &lt;complexType&gt;
 *             &lt;complexContent&gt;
 *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
 *                 &lt;sequence&gt;
 *                   &lt;element name="Property" type="{http://www.fleetboard.com/data}PropertyType" maxOccurs="unbounded" minOccurs="0"/&gt;
 *                 &lt;/sequence&gt;
 *               &lt;/restriction&gt;
 *             &lt;/complexContent&gt;
 *           &lt;/complexType&gt;
 *         &lt;/element&gt;
 *       &lt;/sequence&gt;
 *       &lt;attribute name="inoid" type="{http://www.fleetboard.com/data}inoidType" /&gt;
 *     &lt;/restriction&gt;
 *   &lt;/complexContent&gt;
 * &lt;/complexType&gt;
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "fleetid",
    "fleetname",
    "fleetinformation",
    "fleetrights",
    "fleetproperties"
})
@XmlRootElement(name = "FLEET")
public class FLEET {

    @XmlElement(name = "FLEETID")
    protected long fleetid;
    @XmlElement(name = "FLEETNAME", required = true)
    protected String fleetname;
    @XmlElement(name = "FLEETINFORMATION", required = true, nillable = true)
    protected FLEET.FLEETINFORMATION fleetinformation;
    @XmlElement(name = "FLEETRIGHTS", required = true, nillable = true)
    protected FLEET.FLEETRIGHTS fleetrights;
    @XmlElement(name = "FLEETPROPERTIES", required = true, nillable = true)
    protected FLEET.FLEETPROPERTIES fleetproperties;
    @XmlAttribute(name = "inoid")
    protected String inoid;

    /**
     * Gets the value of the fleetid property.
     * 
     */
    public long getFLEETID() {
        return fleetid;
    }

    /**
     * Sets the value of the fleetid property.
     * 
     */
    public void setFLEETID(long value) {
        this.fleetid = value;
    }

    /**
     * Gets the value of the fleetname property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getFLEETNAME() {
        return fleetname;
    }

    /**
     * Sets the value of the fleetname property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setFLEETNAME(String value) {
        this.fleetname = value;
    }

    /**
     * Gets the value of the fleetinformation property.
     * 
     * @return
     *     possible object is
     *     {@link FLEET.FLEETINFORMATION }
     *     
     */
    public FLEET.FLEETINFORMATION getFLEETINFORMATION() {
        return fleetinformation;
    }

    /**
     * Sets the value of the fleetinformation property.
     * 
     * @param value
     *     allowed object is
     *     {@link FLEET.FLEETINFORMATION }
     *     
     */
    public void setFLEETINFORMATION(FLEET.FLEETINFORMATION value) {
        this.fleetinformation = value;
    }

    /**
     * Gets the value of the fleetrights property.
     * 
     * @return
     *     possible object is
     *     {@link FLEET.FLEETRIGHTS }
     *     
     */
    public FLEET.FLEETRIGHTS getFLEETRIGHTS() {
        return fleetrights;
    }

    /**
     * Sets the value of the fleetrights property.
     * 
     * @param value
     *     allowed object is
     *     {@link FLEET.FLEETRIGHTS }
     *     
     */
    public void setFLEETRIGHTS(FLEET.FLEETRIGHTS value) {
        this.fleetrights = value;
    }

    /**
     * Gets the value of the fleetproperties property.
     * 
     * @return
     *     possible object is
     *     {@link FLEET.FLEETPROPERTIES }
     *     
     */
    public FLEET.FLEETPROPERTIES getFLEETPROPERTIES() {
        return fleetproperties;
    }

    /**
     * Sets the value of the fleetproperties property.
     * 
     * @param value
     *     allowed object is
     *     {@link FLEET.FLEETPROPERTIES }
     *     
     */
    public void setFLEETPROPERTIES(FLEET.FLEETPROPERTIES value) {
        this.fleetproperties = value;
    }

    /**
     * Gets the value of the inoid property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getInoid() {
        return inoid;
    }

    /**
     * Sets the value of the inoid property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setInoid(String value) {
        this.inoid = value;
    }


    /**
     * <p>Java class for anonymous complex type.
     * 
     * <p>The following schema fragment specifies the expected content contained within this class.
     * 
     * <pre>
     * &lt;complexType&gt;
     *   &lt;complexContent&gt;
     *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
     *       &lt;sequence&gt;
     *         &lt;element name="STREET" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/&gt;
     *         &lt;element name="POSTALCODE" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/&gt;
     *         &lt;element name="CITY" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/&gt;
     *         &lt;element name="COUNTRY" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/&gt;
     *         &lt;element name="COUNTRYCODE" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/&gt;
     *         &lt;element name="REGION" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/&gt;
     *         &lt;element name="REGIONCODE" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/&gt;
     *         &lt;element name="PAGEHEADING" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/&gt;
     *         &lt;element name="FLEETTIMEZONE" type="{http://www.w3.org/2001/XMLSchema}integer" minOccurs="0"/&gt;
     *         &lt;element name="FLEETTIMEZONEID" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/&gt;
     *         &lt;element name="DLSAVING" type="{http://www.w3.org/2001/XMLSchema}integer" minOccurs="0"/&gt;
     *         &lt;element name="DELTAETAMON" type="{http://www.w3.org/2001/XMLSchema}integer" minOccurs="0"/&gt;
     *         &lt;element name="DELTAAREAMON" type="{http://www.w3.org/2001/XMLSchema}integer" minOccurs="0"/&gt;
     *       &lt;/sequence&gt;
     *     &lt;/restriction&gt;
     *   &lt;/complexContent&gt;
     * &lt;/complexType&gt;
     * </pre>
     * 
     * 
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "", propOrder = {
        "street",
        "postalcode",
        "city",
        "country",
        "countrycode",
        "region",
        "regioncode",
        "pageheading",
        "fleettimezone",
        "fleettimezoneid",
        "dlsaving",
        "deltaetamon",
        "deltaareamon"
    })
    public static class FLEETINFORMATION {

        @XmlElement(name = "STREET")
        protected String street;
        @XmlElement(name = "POSTALCODE")
        protected String postalcode;
        @XmlElement(name = "CITY")
        protected String city;
        @XmlElement(name = "COUNTRY")
        protected String country;
        @XmlElement(name = "COUNTRYCODE")
        protected String countrycode;
        @XmlElement(name = "REGION")
        protected String region;
        @XmlElement(name = "REGIONCODE")
        protected String regioncode;
        @XmlElement(name = "PAGEHEADING")
        protected String pageheading;
        @XmlElement(name = "FLEETTIMEZONE")
        protected BigInteger fleettimezone;
        @XmlElement(name = "FLEETTIMEZONEID")
        protected String fleettimezoneid;
        @XmlElement(name = "DLSAVING")
        protected BigInteger dlsaving;
        @XmlElement(name = "DELTAETAMON")
        protected BigInteger deltaetamon;
        @XmlElement(name = "DELTAAREAMON")
        protected BigInteger deltaareamon;

        /**
         * Gets the value of the street property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getSTREET() {
            return street;
        }

        /**
         * Sets the value of the street property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setSTREET(String value) {
            this.street = value;
        }

        /**
         * Gets the value of the postalcode property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getPOSTALCODE() {
            return postalcode;
        }

        /**
         * Sets the value of the postalcode property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setPOSTALCODE(String value) {
            this.postalcode = value;
        }

        /**
         * Gets the value of the city property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getCITY() {
            return city;
        }

        /**
         * Sets the value of the city property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setCITY(String value) {
            this.city = value;
        }

        /**
         * Gets the value of the country property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getCOUNTRY() {
            return country;
        }

        /**
         * Sets the value of the country property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setCOUNTRY(String value) {
            this.country = value;
        }

        /**
         * Gets the value of the countrycode property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getCOUNTRYCODE() {
            return countrycode;
        }

        /**
         * Sets the value of the countrycode property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setCOUNTRYCODE(String value) {
            this.countrycode = value;
        }

        /**
         * Gets the value of the region property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getREGION() {
            return region;
        }

        /**
         * Sets the value of the region property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setREGION(String value) {
            this.region = value;
        }

        /**
         * Gets the value of the regioncode property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getREGIONCODE() {
            return regioncode;
        }

        /**
         * Sets the value of the regioncode property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setREGIONCODE(String value) {
            this.regioncode = value;
        }

        /**
         * Gets the value of the pageheading property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getPAGEHEADING() {
            return pageheading;
        }

        /**
         * Sets the value of the pageheading property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setPAGEHEADING(String value) {
            this.pageheading = value;
        }

        /**
         * Gets the value of the fleettimezone property.
         * 
         * @return
         *     possible object is
         *     {@link BigInteger }
         *     
         */
        public BigInteger getFLEETTIMEZONE() {
            return fleettimezone;
        }

        /**
         * Sets the value of the fleettimezone property.
         * 
         * @param value
         *     allowed object is
         *     {@link BigInteger }
         *     
         */
        public void setFLEETTIMEZONE(BigInteger value) {
            this.fleettimezone = value;
        }

        /**
         * Gets the value of the fleettimezoneid property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getFLEETTIMEZONEID() {
            return fleettimezoneid;
        }

        /**
         * Sets the value of the fleettimezoneid property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setFLEETTIMEZONEID(String value) {
            this.fleettimezoneid = value;
        }

        /**
         * Gets the value of the dlsaving property.
         * 
         * @return
         *     possible object is
         *     {@link BigInteger }
         *     
         */
        public BigInteger getDLSAVING() {
            return dlsaving;
        }

        /**
         * Sets the value of the dlsaving property.
         * 
         * @param value
         *     allowed object is
         *     {@link BigInteger }
         *     
         */
        public void setDLSAVING(BigInteger value) {
            this.dlsaving = value;
        }

        /**
         * Gets the value of the deltaetamon property.
         * 
         * @return
         *     possible object is
         *     {@link BigInteger }
         *     
         */
        public BigInteger getDELTAETAMON() {
            return deltaetamon;
        }

        /**
         * Sets the value of the deltaetamon property.
         * 
         * @param value
         *     allowed object is
         *     {@link BigInteger }
         *     
         */
        public void setDELTAETAMON(BigInteger value) {
            this.deltaetamon = value;
        }

        /**
         * Gets the value of the deltaareamon property.
         * 
         * @return
         *     possible object is
         *     {@link BigInteger }
         *     
         */
        public BigInteger getDELTAAREAMON() {
            return deltaareamon;
        }

        /**
         * Sets the value of the deltaareamon property.
         * 
         * @param value
         *     allowed object is
         *     {@link BigInteger }
         *     
         */
        public void setDELTAAREAMON(BigInteger value) {
            this.deltaareamon = value;
        }

    }


    /**
     * <p>Java class for anonymous complex type.
     * 
     * <p>The following schema fragment specifies the expected content contained within this class.
     * 
     * <pre>
     * &lt;complexType&gt;
     *   &lt;complexContent&gt;
     *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
     *       &lt;sequence&gt;
     *         &lt;element name="Property" type="{http://www.fleetboard.com/data}PropertyType" maxOccurs="unbounded" minOccurs="0"/&gt;
     *       &lt;/sequence&gt;
     *     &lt;/restriction&gt;
     *   &lt;/complexContent&gt;
     * &lt;/complexType&gt;
     * </pre>
     * 
     * 
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "", propOrder = {
        "property"
    })
    public static class FLEETPROPERTIES {

        @XmlElement(name = "Property")
        protected List<PropertyType> property;

        /**
         * Gets the value of the property property.
         * 
         * <p>
         * This accessor method returns a reference to the live list,
         * not a snapshot. Therefore any modification you make to the
         * returned list will be present inside the JAXB object.
         * This is why there is not a <CODE>set</CODE> method for the property property.
         * 
         * <p>
         * For example, to add a new item, do as follows:
         * <pre>
         *    getProperty().add(newItem);
         * </pre>
         * 
         * 
         * <p>
         * Objects of the following type(s) are allowed in the list
         * {@link PropertyType }
         * 
         * 
         */
        public List<PropertyType> getProperty() {
            if (property == null) {
                property = new ArrayList<PropertyType>();
            }
            return this.property;
        }

    }


    /**
     * <p>Java class for anonymous complex type.
     * 
     * <p>The following schema fragment specifies the expected content contained within this class.
     * 
     * <pre>
     * &lt;complexType&gt;
     *   &lt;complexContent&gt;
     *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
     *       &lt;sequence&gt;
     *         &lt;element ref="{http://www.fleetboard.com/data}RIGHT" maxOccurs="unbounded" minOccurs="0"/&gt;
     *       &lt;/sequence&gt;
     *     &lt;/restriction&gt;
     *   &lt;/complexContent&gt;
     * &lt;/complexType&gt;
     * </pre>
     * 
     * 
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "", propOrder = {
        "right"
    })
    public static class FLEETRIGHTS {

        @XmlElement(name = "RIGHT")
        protected List<RIGHT> right;

        /**
         * Gets the value of the right property.
         * 
         * <p>
         * This accessor method returns a reference to the live list,
         * not a snapshot. Therefore any modification you make to the
         * returned list will be present inside the JAXB object.
         * This is why there is not a <CODE>set</CODE> method for the right property.
         * 
         * <p>
         * For example, to add a new item, do as follows:
         * <pre>
         *    getRIGHT().add(newItem);
         * </pre>
         * 
         * 
         * <p>
         * Objects of the following type(s) are allowed in the list
         * {@link RIGHT }
         * 
         * 
         */
        public List<RIGHT> getRIGHT() {
            if (right == null) {
                right = new ArrayList<RIGHT>();
            }
            return this.right;
        }

    }

}
