//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.11 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2017.09.06 at 01:34:55 AM CEST 
//


package pl.oskarpolak.automatic.models.soap.basicservice;

import java.math.BigInteger;
import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for GetStatusDefRequestType complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="GetStatusDefRequestType"&gt;
 *   &lt;complexContent&gt;
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
 *       &lt;sequence&gt;
 *         &lt;element name="Kind" maxOccurs="unbounded" minOccurs="0"&gt;
 *           &lt;simpleType&gt;
 *             &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string"&gt;
 *               &lt;enumeration value="VEHICLE"/&gt;
 *               &lt;enumeration value="ORDER"/&gt;
 *               &lt;enumeration value="TOUR"/&gt;
 *               &lt;enumeration value="CLIENT"/&gt;
 *               &lt;enumeration value="TIMEMGMT"/&gt;
 *               &lt;enumeration value="EVENT"/&gt;
 *             &lt;/restriction&gt;
 *           &lt;/simpleType&gt;
 *         &lt;/element&gt;
 *         &lt;element name="Inoid" type="{http://www.fleetboard.com/data}inoidType" maxOccurs="unbounded" minOccurs="0"/&gt;
 *         &lt;element name="Fbid" type="{http://www.fleetboard.com/data}fbidType" maxOccurs="unbounded" minOccurs="0"/&gt;
 *         &lt;element name="MultiFleet" type="{http://www.w3.org/2001/XMLSchema}boolean" minOccurs="0"/&gt;
 *         &lt;element name="TmConfigId" type="{http://www.fleetboard.com/data}tmConfigIdType" minOccurs="0"/&gt;
 *       &lt;/sequence&gt;
 *       &lt;attribute name="limit" type="{http://www.fleetboard.com/data}limitType" /&gt;
 *       &lt;attribute name="offset" type="{http://www.fleetboard.com/data}offsetType" /&gt;
 *       &lt;attribute name="version" type="{http://www.fleetboard.com/data}versionType" /&gt;
 *     &lt;/restriction&gt;
 *   &lt;/complexContent&gt;
 * &lt;/complexType&gt;
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "GetStatusDefRequestType", propOrder = {
    "kind",
    "inoid",
    "fbid",
    "multiFleet",
    "tmConfigId"
})
public class GetStatusDefRequestType {

    @XmlElement(name = "Kind")
    protected List<String> kind;
    @XmlElement(name = "Inoid")
    protected List<String> inoid;
    @XmlElement(name = "Fbid")
    protected List<String> fbid;
    @XmlElement(name = "MultiFleet")
    protected Boolean multiFleet;
    @XmlElement(name = "TmConfigId")
    protected Long tmConfigId;
    @XmlAttribute(name = "limit")
    protected BigInteger limit;
    @XmlAttribute(name = "offset")
    protected BigInteger offset;
    @XmlAttribute(name = "version")
    protected Long version;

    /**
     * Gets the value of the kind property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the kind property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getKind().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link String }
     * 
     * 
     */
    public List<String> getKind() {
        if (kind == null) {
            kind = new ArrayList<String>();
        }
        return this.kind;
    }

    /**
     * Gets the value of the inoid property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the inoid property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getInoid().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link String }
     * 
     * 
     */
    public List<String> getInoid() {
        if (inoid == null) {
            inoid = new ArrayList<String>();
        }
        return this.inoid;
    }

    /**
     * Gets the value of the fbid property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the fbid property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getFbid().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link String }
     * 
     * 
     */
    public List<String> getFbid() {
        if (fbid == null) {
            fbid = new ArrayList<String>();
        }
        return this.fbid;
    }

    /**
     * Gets the value of the multiFleet property.
     * 
     * @return
     *     possible object is
     *     {@link Boolean }
     *     
     */
    public Boolean isMultiFleet() {
        return multiFleet;
    }

    /**
     * Sets the value of the multiFleet property.
     * 
     * @param value
     *     allowed object is
     *     {@link Boolean }
     *     
     */
    public void setMultiFleet(Boolean value) {
        this.multiFleet = value;
    }

    /**
     * Gets the value of the tmConfigId property.
     * 
     * @return
     *     possible object is
     *     {@link Long }
     *     
     */
    public Long getTmConfigId() {
        return tmConfigId;
    }

    /**
     * Sets the value of the tmConfigId property.
     * 
     * @param value
     *     allowed object is
     *     {@link Long }
     *     
     */
    public void setTmConfigId(Long value) {
        this.tmConfigId = value;
    }

    /**
     * Gets the value of the limit property.
     * 
     * @return
     *     possible object is
     *     {@link BigInteger }
     *     
     */
    public BigInteger getLimit() {
        return limit;
    }

    /**
     * Sets the value of the limit property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigInteger }
     *     
     */
    public void setLimit(BigInteger value) {
        this.limit = value;
    }

    /**
     * Gets the value of the offset property.
     * 
     * @return
     *     possible object is
     *     {@link BigInteger }
     *     
     */
    public BigInteger getOffset() {
        return offset;
    }

    /**
     * Sets the value of the offset property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigInteger }
     *     
     */
    public void setOffset(BigInteger value) {
        this.offset = value;
    }

    /**
     * Gets the value of the version property.
     * 
     * @return
     *     possible object is
     *     {@link Long }
     *     
     */
    public Long getVersion() {
        return version;
    }

    /**
     * Sets the value of the version property.
     * 
     * @param value
     *     allowed object is
     *     {@link Long }
     *     
     */
    public void setVersion(Long value) {
        this.version = value;
    }

}
