//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.11 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2017.09.06 at 01:34:55 AM CEST 
//


package pl.oskarpolak.automatic.models.soap.basicservice;

import javax.xml.bind.JAXBElement;
import javax.xml.bind.annotation.XmlElementDecl;
import javax.xml.bind.annotation.XmlRegistry;
import javax.xml.namespace.QName;


/**
 * This object contains factory methods for each 
 * Java content interface and Java element interface 
 * generated in the pl.oskarpolak.automatic.models.soap.basicservice package. 
 * <p>An ObjectFactory allows you to programatically 
 * construct new instances of the Java representation 
 * for XML content. The Java representation of XML 
 * content can consist of schema derived interfaces 
 * and classes representing the binding of schema 
 * type definitions, element declarations and model 
 * groups.  Factory methods for each of these are 
 * provided in this class.
 * 
 */
@XmlRegistry
public class ObjectFactory {

    private final static QName _GetStatusDefRequest_QNAME = new QName("http://www.fleetboard.com/data", "GetStatusDefRequest");
    private final static QName _Hidden_QNAME = new QName("http://www.fleetboard.com/data", "Hidden");
    private final static QName _VhcStatusLayout_QNAME = new QName("http://www.fleetboard.com/data", "VhcStatusLayout");
    private final static QName _GetStatusDefResponse_QNAME = new QName("http://www.fleetboard.com/data", "GetStatusDefResponse");
    private final static QName _GetUserResponse_QNAME = new QName("http://www.fleetboard.com/data", "GetUserResponse");
    private final static QName _GetDriverRequest_QNAME = new QName("http://www.fleetboard.com/data", "GetDriverRequest");
    private final static QName _GetDriverResponse_QNAME = new QName("http://www.fleetboard.com/data", "GetDriverResponse");
    private final static QName _GetCurrentUserResponse_QNAME = new QName("http://www.fleetboard.com/data", "GetCurrentUserResponse");

    /**
     * Create a new ObjectFactory that can be used to create new instances of schema derived classes for package: pl.oskarpolak.automatic.models.soap.basicservice
     * 
     */
    public ObjectFactory() {
    }

    /**
     * Create an instance of {@link FLEET }
     * 
     */
    public FLEET createFLEET() {
        return new FLEET();
    }

    /**
     * Create an instance of {@link VEHICLE }
     * 
     */
    public VEHICLE createVEHICLE() {
        return new VEHICLE();
    }

    /**
     * Create an instance of {@link Action }
     * 
     */
    public Action createAction() {
        return new Action();
    }

    /**
     * Create an instance of {@link SemanticsDef }
     * 
     */
    public SemanticsDef createSemanticsDef() {
        return new SemanticsDef();
    }

    /**
     * Create an instance of {@link StatusDef }
     * 
     */
    public StatusDef createStatusDef() {
        return new StatusDef();
    }

    /**
     * Create an instance of {@link TmSoapUserType }
     * 
     */
    public TmSoapUserType createTmSoapUserType() {
        return new TmSoapUserType();
    }

    /**
     * Create an instance of {@link ErrorType }
     * 
     */
    public ErrorType createErrorType() {
        return new ErrorType();
    }

    /**
     * Create an instance of {@link OkType }
     * 
     */
    public OkType createOkType() {
        return new OkType();
    }

    /**
     * Create an instance of {@link ErrorResultType }
     * 
     */
    public ErrorResultType createErrorResultType() {
        return new ErrorResultType();
    }

    /**
     * Create an instance of {@link OkResultType }
     * 
     */
    public OkResultType createOkResultType() {
        return new OkResultType();
    }

    /**
     * Create an instance of {@link GetDriverResponseType }
     * 
     */
    public GetDriverResponseType createGetDriverResponseType() {
        return new GetDriverResponseType();
    }

    /**
     * Create an instance of {@link GetDriverResponseType.DriverInfo }
     * 
     */
    public GetDriverResponseType.DriverInfo createGetDriverResponseTypeDriverInfo() {
        return new GetDriverResponseType.DriverInfo();
    }

    /**
     * Create an instance of {@link LoginResponse }
     * 
     */
    public LoginResponse createLoginResponse() {
        return new LoginResponse();
    }

    /**
     * Create an instance of {@link LogoutRequest }
     * 
     */
    public LogoutRequest createLogoutRequest() {
        return new LogoutRequest();
    }

    /**
     * Create an instance of {@link LogoutResponse }
     * 
     */
    public LogoutResponse createLogoutResponse() {
        return new LogoutResponse();
    }

    /**
     * Create an instance of {@link GetFleetRequest }
     * 
     */
    public GetFleetRequest createGetFleetRequest() {
        return new GetFleetRequest();
    }

    /**
     * Create an instance of {@link RIGHT }
     * 
     */
    public RIGHT createRIGHT() {
        return new RIGHT();
    }

    /**
     * Create an instance of {@link FLEET.FLEETINFORMATION }
     * 
     */
    public FLEET.FLEETINFORMATION createFLEETFLEETINFORMATION() {
        return new FLEET.FLEETINFORMATION();
    }

    /**
     * Create an instance of {@link FLEET.FLEETRIGHTS }
     * 
     */
    public FLEET.FLEETRIGHTS createFLEETFLEETRIGHTS() {
        return new FLEET.FLEETRIGHTS();
    }

    /**
     * Create an instance of {@link FLEET.FLEETPROPERTIES }
     * 
     */
    public FLEET.FLEETPROPERTIES createFLEETFLEETPROPERTIES() {
        return new FLEET.FLEETPROPERTIES();
    }

    /**
     * Create an instance of {@link GetFleetResponse }
     * 
     */
    public GetFleetResponse createGetFleetResponse() {
        return new GetFleetResponse();
    }

    /**
     * Create an instance of {@link GetVehicleRequest }
     * 
     */
    public GetVehicleRequest createGetVehicleRequest() {
        return new GetVehicleRequest();
    }

    /**
     * Create an instance of {@link DtcoCapabilityType }
     * 
     */
    public DtcoCapabilityType createDtcoCapabilityType() {
        return new DtcoCapabilityType();
    }

    /**
     * Create an instance of {@link VEHICLE.VEHICLEHARDWARE }
     * 
     */
    public VEHICLE.VEHICLEHARDWARE createVEHICLEVEHICLEHARDWARE() {
        return new VEHICLE.VEHICLEHARDWARE();
    }

    /**
     * Create an instance of {@link VEHICLE.FLEETVEHICLE }
     * 
     */
    public VEHICLE.FLEETVEHICLE createVEHICLEFLEETVEHICLE() {
        return new VEHICLE.FLEETVEHICLE();
    }

    /**
     * Create an instance of {@link VEHICLE.GROUPVEHICLE }
     * 
     */
    public VEHICLE.GROUPVEHICLE createVEHICLEGROUPVEHICLE() {
        return new VEHICLE.GROUPVEHICLE();
    }

    /**
     * Create an instance of {@link VEHICLE.VEHICLEPROPERTIES }
     * 
     */
    public VEHICLE.VEHICLEPROPERTIES createVEHICLEVEHICLEPROPERTIES() {
        return new VEHICLE.VEHICLEPROPERTIES();
    }

    /**
     * Create an instance of {@link GetVehicleResponse }
     * 
     */
    public GetVehicleResponse createGetVehicleResponse() {
        return new GetVehicleResponse();
    }

    /**
     * Create an instance of {@link GetVehicleGroupRequest }
     * 
     */
    public GetVehicleGroupRequest createGetVehicleGroupRequest() {
        return new GetVehicleGroupRequest();
    }

    /**
     * Create an instance of {@link VEHICLEGROUP }
     * 
     */
    public VEHICLEGROUP createVEHICLEGROUP() {
        return new VEHICLEGROUP();
    }

    /**
     * Create an instance of {@link GetVehicleGroupResponse }
     * 
     */
    public GetVehicleGroupResponse createGetVehicleGroupResponse() {
        return new GetVehicleGroupResponse();
    }

    /**
     * Create an instance of {@link GetServerPropertiesRequest }
     * 
     */
    public GetServerPropertiesRequest createGetServerPropertiesRequest() {
        return new GetServerPropertiesRequest();
    }

    /**
     * Create an instance of {@link GetServerPropertiesResponse }
     * 
     */
    public GetServerPropertiesResponse createGetServerPropertiesResponse() {
        return new GetServerPropertiesResponse();
    }

    /**
     * Create an instance of {@link PropertyType }
     * 
     */
    public PropertyType createPropertyType() {
        return new PropertyType();
    }

    /**
     * Create an instance of {@link GetStatusDefRequestType }
     * 
     */
    public GetStatusDefRequestType createGetStatusDefRequestType() {
        return new GetStatusDefRequestType();
    }

    /**
     * Create an instance of {@link User }
     * 
     */
    public User createUser() {
        return new User();
    }

    /**
     * Create an instance of {@link History }
     * 
     */
    public History createHistory() {
        return new History();
    }

    /**
     * Create an instance of {@link TXMessage }
     * 
     */
    public TXMessage createTXMessage() {
        return new TXMessage();
    }

    /**
     * Create an instance of {@link RXMessage }
     * 
     */
    public RXMessage createRXMessage() {
        return new RXMessage();
    }

    /**
     * Create an instance of {@link Action.Request }
     * 
     */
    public Action.Request createActionRequest() {
        return new Action.Request();
    }

    /**
     * Create an instance of {@link StatusLayout }
     * 
     */
    public StatusLayout createStatusLayout() {
        return new StatusLayout();
    }

    /**
     * Create an instance of {@link Hidden }
     * 
     */
    public Hidden createHidden() {
        return new Hidden();
    }

    /**
     * Create an instance of {@link VhcStatusLayout }
     * 
     */
    public VhcStatusLayout createVhcStatusLayout() {
        return new VhcStatusLayout();
    }

    /**
     * Create an instance of {@link SemanticsDef.Semantics }
     * 
     */
    public SemanticsDef.Semantics createSemanticsDefSemantics() {
        return new SemanticsDef.Semantics();
    }

    /**
     * Create an instance of {@link StatusDef.Type }
     * 
     */
    public StatusDef.Type createStatusDefType() {
        return new StatusDef.Type();
    }

    /**
     * Create an instance of {@link GetStatusDefResponseType }
     * 
     */
    public GetStatusDefResponseType createGetStatusDefResponseType() {
        return new GetStatusDefResponseType();
    }

    /**
     * Create an instance of {@link GetUserRequest }
     * 
     */
    public GetUserRequest createGetUserRequest() {
        return new GetUserRequest();
    }

    /**
     * Create an instance of {@link GetUserResponseType }
     * 
     */
    public GetUserResponseType createGetUserResponseType() {
        return new GetUserResponseType();
    }

    /**
     * Create an instance of {@link GetDriverRequestType }
     * 
     */
    public GetDriverRequestType createGetDriverRequestType() {
        return new GetDriverRequestType();
    }

    /**
     * Create an instance of {@link GetCurrentUserRequest }
     * 
     */
    public GetCurrentUserRequest createGetCurrentUserRequest() {
        return new GetCurrentUserRequest();
    }

    /**
     * Create an instance of {@link GetCurrentUserResponseType }
     * 
     */
    public GetCurrentUserResponseType createGetCurrentUserResponseType() {
        return new GetCurrentUserResponseType();
    }

    /**
     * Create an instance of {@link GetDriverGroupRequest }
     * 
     */
    public GetDriverGroupRequest createGetDriverGroupRequest() {
        return new GetDriverGroupRequest();
    }

    /**
     * Create an instance of {@link pl.oskarpolak.automatic.models.soap.basicservice.DriverGroup }
     * 
     */
    public pl.oskarpolak.automatic.models.soap.basicservice.DriverGroup createDriverGroup() {
        return new pl.oskarpolak.automatic.models.soap.basicservice.DriverGroup();
    }

    /**
     * Create an instance of {@link GetDriverGroupResponse }
     * 
     */
    public GetDriverGroupResponse createGetDriverGroupResponse() {
        return new GetDriverGroupResponse();
    }

    /**
     * Create an instance of {@link LoginRequest }
     * 
     */
    public LoginRequest createLoginRequest() {
        return new LoginRequest();
    }

    /**
     * Create an instance of {@link Login }
     * 
     */
    public Login createLogin() {
        return new Login();
    }

    /**
     * Create an instance of {@link LoginResponse2 }
     * 
     */
    public LoginResponse2 createLoginResponse2() {
        return new LoginResponse2();
    }

    /**
     * Create an instance of {@link Logout }
     * 
     */
    public Logout createLogout() {
        return new Logout();
    }

    /**
     * Create an instance of {@link LogoutResponse2 }
     * 
     */
    public LogoutResponse2 createLogoutResponse2() {
        return new LogoutResponse2();
    }

    /**
     * Create an instance of {@link GetFleet }
     * 
     */
    public GetFleet createGetFleet() {
        return new GetFleet();
    }

    /**
     * Create an instance of {@link GetFleetResponse2 }
     * 
     */
    public GetFleetResponse2 createGetFleetResponse2() {
        return new GetFleetResponse2();
    }

    /**
     * Create an instance of {@link GetVehicle }
     * 
     */
    public GetVehicle createGetVehicle() {
        return new GetVehicle();
    }

    /**
     * Create an instance of {@link GetVehicleResponse2 }
     * 
     */
    public GetVehicleResponse2 createGetVehicleResponse2() {
        return new GetVehicleResponse2();
    }

    /**
     * Create an instance of {@link GetVehicleGroup }
     * 
     */
    public GetVehicleGroup createGetVehicleGroup() {
        return new GetVehicleGroup();
    }

    /**
     * Create an instance of {@link GetVehicleGroupResponse2 }
     * 
     */
    public GetVehicleGroupResponse2 createGetVehicleGroupResponse2() {
        return new GetVehicleGroupResponse2();
    }

    /**
     * Create an instance of {@link GetServerProperties }
     * 
     */
    public GetServerProperties createGetServerProperties() {
        return new GetServerProperties();
    }

    /**
     * Create an instance of {@link GetServerPropertiesResponse2 }
     * 
     */
    public GetServerPropertiesResponse2 createGetServerPropertiesResponse2() {
        return new GetServerPropertiesResponse2();
    }

    /**
     * Create an instance of {@link GetStatusDef }
     * 
     */
    public GetStatusDef createGetStatusDef() {
        return new GetStatusDef();
    }

    /**
     * Create an instance of {@link GetStatusDefResponse }
     * 
     */
    public GetStatusDefResponse createGetStatusDefResponse() {
        return new GetStatusDefResponse();
    }

    /**
     * Create an instance of {@link GetUser }
     * 
     */
    public GetUser createGetUser() {
        return new GetUser();
    }

    /**
     * Create an instance of {@link GetUserResponse }
     * 
     */
    public GetUserResponse createGetUserResponse() {
        return new GetUserResponse();
    }

    /**
     * Create an instance of {@link GetDriver }
     * 
     */
    public GetDriver createGetDriver() {
        return new GetDriver();
    }

    /**
     * Create an instance of {@link GetDriverResponse }
     * 
     */
    public GetDriverResponse createGetDriverResponse() {
        return new GetDriverResponse();
    }

    /**
     * Create an instance of {@link GetCurrentUser }
     * 
     */
    public GetCurrentUser createGetCurrentUser() {
        return new GetCurrentUser();
    }

    /**
     * Create an instance of {@link GetCurrentUserResponse }
     * 
     */
    public GetCurrentUserResponse createGetCurrentUserResponse() {
        return new GetCurrentUserResponse();
    }

    /**
     * Create an instance of {@link GetDriverGroup }
     * 
     */
    public GetDriverGroup createGetDriverGroup() {
        return new GetDriverGroup();
    }

    /**
     * Create an instance of {@link GetDriverGroupResponse2 }
     * 
     */
    public GetDriverGroupResponse2 createGetDriverGroupResponse2() {
        return new GetDriverGroupResponse2();
    }

    /**
     * Create an instance of {@link TPDate }
     * 
     */
    public TPDate createTPDate() {
        return new TPDate();
    }

    /**
     * Create an instance of {@link TmSoapUserType.UserSettings }
     * 
     */
    public TmSoapUserType.UserSettings createTmSoapUserTypeUserSettings() {
        return new TmSoapUserType.UserSettings();
    }

    /**
     * Create an instance of {@link TmSoapUserType.RightSettings }
     * 
     */
    public TmSoapUserType.RightSettings createTmSoapUserTypeRightSettings() {
        return new TmSoapUserType.RightSettings();
    }

    /**
     * Create an instance of {@link ErrorType.ErrorResult }
     * 
     */
    public ErrorType.ErrorResult createErrorTypeErrorResult() {
        return new ErrorType.ErrorResult();
    }

    /**
     * Create an instance of {@link OkType.OKResult }
     * 
     */
    public OkType.OKResult createOkTypeOKResult() {
        return new OkType.OKResult();
    }

    /**
     * Create an instance of {@link ErrorResultType.ErrorResult }
     * 
     */
    public ErrorResultType.ErrorResult createErrorResultTypeErrorResult() {
        return new ErrorResultType.ErrorResult();
    }

    /**
     * Create an instance of {@link OkResultType.OKResult }
     * 
     */
    public OkResultType.OKResult createOkResultTypeOKResult() {
        return new OkResultType.OKResult();
    }

    /**
     * Create an instance of {@link GetDriverResponseType.DriverInfo.DriverToken }
     * 
     */
    public GetDriverResponseType.DriverInfo.DriverToken createGetDriverResponseTypeDriverInfoDriverToken() {
        return new GetDriverResponseType.DriverInfo.DriverToken();
    }

    /**
     * Create an instance of {@link GetDriverResponseType.DriverInfo.DriverGroup }
     * 
     */
    public GetDriverResponseType.DriverInfo.DriverGroup createGetDriverResponseTypeDriverInfoDriverGroup() {
        return new GetDriverResponseType.DriverInfo.DriverGroup();
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link GetStatusDefRequestType }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://www.fleetboard.com/data", name = "GetStatusDefRequest")
    public JAXBElement<GetStatusDefRequestType> createGetStatusDefRequest(GetStatusDefRequestType value) {
        return new JAXBElement<GetStatusDefRequestType>(_GetStatusDefRequest_QNAME, GetStatusDefRequestType.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link Hidden }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://www.fleetboard.com/data", name = "Hidden")
    public JAXBElement<Hidden> createHidden(Hidden value) {
        return new JAXBElement<Hidden>(_Hidden_QNAME, Hidden.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link VhcStatusLayout }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://www.fleetboard.com/data", name = "VhcStatusLayout")
    public JAXBElement<VhcStatusLayout> createVhcStatusLayout(VhcStatusLayout value) {
        return new JAXBElement<VhcStatusLayout>(_VhcStatusLayout_QNAME, VhcStatusLayout.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link GetStatusDefResponseType }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://www.fleetboard.com/data", name = "GetStatusDefResponse")
    public JAXBElement<GetStatusDefResponseType> createGetStatusDefResponse(GetStatusDefResponseType value) {
        return new JAXBElement<GetStatusDefResponseType>(_GetStatusDefResponse_QNAME, GetStatusDefResponseType.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link GetUserResponseType }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://www.fleetboard.com/data", name = "GetUserResponse")
    public JAXBElement<GetUserResponseType> createGetUserResponse(GetUserResponseType value) {
        return new JAXBElement<GetUserResponseType>(_GetUserResponse_QNAME, GetUserResponseType.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link GetDriverRequestType }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://www.fleetboard.com/data", name = "GetDriverRequest")
    public JAXBElement<GetDriverRequestType> createGetDriverRequest(GetDriverRequestType value) {
        return new JAXBElement<GetDriverRequestType>(_GetDriverRequest_QNAME, GetDriverRequestType.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link GetDriverResponseType }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://www.fleetboard.com/data", name = "GetDriverResponse")
    public JAXBElement<GetDriverResponseType> createGetDriverResponse(GetDriverResponseType value) {
        return new JAXBElement<GetDriverResponseType>(_GetDriverResponse_QNAME, GetDriverResponseType.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link GetCurrentUserResponseType }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://www.fleetboard.com/data", name = "GetCurrentUserResponse")
    public JAXBElement<GetCurrentUserResponseType> createGetCurrentUserResponse(GetCurrentUserResponseType value) {
        return new JAXBElement<GetCurrentUserResponseType>(_GetCurrentUserResponse_QNAME, GetCurrentUserResponseType.class, null, value);
    }

}
