//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.11 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2017.09.06 at 01:34:55 AM CEST 
//

@javax.xml.bind.annotation.XmlSchema(namespace = "http://www.fleetboard.com/data", elementFormDefault = javax.xml.bind.annotation.XmlNsForm.QUALIFIED)
package pl.oskarpolak.automatic.models.soap.basicservice;
