//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.11 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2017.09.06 at 01:34:55 AM CEST 
//


package pl.oskarpolak.automatic.models.soap.basicservice;

import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for anonymous complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType&gt;
 *   &lt;complexContent&gt;
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
 *       &lt;sequence&gt;
 *         &lt;element name="Semantics" maxOccurs="unbounded"&gt;
 *           &lt;complexType&gt;
 *             &lt;complexContent&gt;
 *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
 *                 &lt;sequence&gt;
 *                   &lt;element name="Denotation" type="{http://www.w3.org/2001/XMLSchema}string"/&gt;
 *                   &lt;element name="SemanticId" type="{http://www.w3.org/2001/XMLSchema}long" minOccurs="0"/&gt;
 *                   &lt;element name="Scope" type="{http://www.w3.org/2001/XMLSchema}string" maxOccurs="unbounded" minOccurs="0"/&gt;
 *                   &lt;element name="Value" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/&gt;
 *                 &lt;/sequence&gt;
 *               &lt;/restriction&gt;
 *             &lt;/complexContent&gt;
 *           &lt;/complexType&gt;
 *         &lt;/element&gt;
 *       &lt;/sequence&gt;
 *     &lt;/restriction&gt;
 *   &lt;/complexContent&gt;
 * &lt;/complexType&gt;
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "semantics"
})
@XmlRootElement(name = "SemanticsDef")
public class SemanticsDef {

    @XmlElement(name = "Semantics", required = true)
    protected List<SemanticsDef.Semantics> semantics;

    /**
     * Gets the value of the semantics property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the semantics property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getSemantics().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link SemanticsDef.Semantics }
     * 
     * 
     */
    public List<SemanticsDef.Semantics> getSemantics() {
        if (semantics == null) {
            semantics = new ArrayList<SemanticsDef.Semantics>();
        }
        return this.semantics;
    }


    /**
     * <p>Java class for anonymous complex type.
     * 
     * <p>The following schema fragment specifies the expected content contained within this class.
     * 
     * <pre>
     * &lt;complexType&gt;
     *   &lt;complexContent&gt;
     *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
     *       &lt;sequence&gt;
     *         &lt;element name="Denotation" type="{http://www.w3.org/2001/XMLSchema}string"/&gt;
     *         &lt;element name="SemanticId" type="{http://www.w3.org/2001/XMLSchema}long" minOccurs="0"/&gt;
     *         &lt;element name="Scope" type="{http://www.w3.org/2001/XMLSchema}string" maxOccurs="unbounded" minOccurs="0"/&gt;
     *         &lt;element name="Value" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/&gt;
     *       &lt;/sequence&gt;
     *     &lt;/restriction&gt;
     *   &lt;/complexContent&gt;
     * &lt;/complexType&gt;
     * </pre>
     * 
     * 
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "", propOrder = {
        "denotation",
        "semanticId",
        "scope",
        "value"
    })
    public static class Semantics {

        @XmlElement(name = "Denotation", required = true)
        protected String denotation;
        @XmlElement(name = "SemanticId")
        protected Long semanticId;
        @XmlElement(name = "Scope")
        protected List<String> scope;
        @XmlElement(name = "Value")
        protected String value;

        /**
         * Gets the value of the denotation property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getDenotation() {
            return denotation;
        }

        /**
         * Sets the value of the denotation property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setDenotation(String value) {
            this.denotation = value;
        }

        /**
         * Gets the value of the semanticId property.
         * 
         * @return
         *     possible object is
         *     {@link Long }
         *     
         */
        public Long getSemanticId() {
            return semanticId;
        }

        /**
         * Sets the value of the semanticId property.
         * 
         * @param value
         *     allowed object is
         *     {@link Long }
         *     
         */
        public void setSemanticId(Long value) {
            this.semanticId = value;
        }

        /**
         * Gets the value of the scope property.
         * 
         * <p>
         * This accessor method returns a reference to the live list,
         * not a snapshot. Therefore any modification you make to the
         * returned list will be present inside the JAXB object.
         * This is why there is not a <CODE>set</CODE> method for the scope property.
         * 
         * <p>
         * For example, to add a new item, do as follows:
         * <pre>
         *    getScope().add(newItem);
         * </pre>
         * 
         * 
         * <p>
         * Objects of the following type(s) are allowed in the list
         * {@link String }
         * 
         * 
         */
        public List<String> getScope() {
            if (scope == null) {
                scope = new ArrayList<String>();
            }
            return this.scope;
        }

        /**
         * Gets the value of the value property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getValue() {
            return value;
        }

        /**
         * Sets the value of the value property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setValue(String value) {
            this.value = value;
        }

    }

}
