//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.11 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2017.09.06 at 01:34:55 AM CEST 
//


package pl.oskarpolak.automatic.models.soap.basicservice;

import java.math.BigInteger;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for anonymous complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType&gt;
 *   &lt;complexContent&gt;
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
 *       &lt;sequence&gt;
 *         &lt;element name="FLEETID" type="{http://www.fleetboard.com/data}fleetidType"/&gt;
 *         &lt;element name="Type"&gt;
 *           &lt;complexType&gt;
 *             &lt;complexContent&gt;
 *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
 *                 &lt;sequence&gt;
 *                   &lt;element name="Kind" type="{http://www.w3.org/2001/XMLSchema}string"/&gt;
 *                   &lt;element name="ATSRegister" type="{http://www.w3.org/2001/XMLSchema}string"/&gt;
 *                 &lt;/sequence&gt;
 *               &lt;/restriction&gt;
 *             &lt;/complexContent&gt;
 *           &lt;/complexType&gt;
 *         &lt;/element&gt;
 *         &lt;element ref="{http://www.fleetboard.com/data}StatusLayout"/&gt;
 *         &lt;element ref="{http://www.fleetboard.com/data}Action"/&gt;
 *         &lt;element ref="{http://www.fleetboard.com/data}History" minOccurs="0"/&gt;
 *         &lt;element name="Visible" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/&gt;
 *         &lt;element name="Showable" type="{http://www.w3.org/2001/XMLSchema}integer" minOccurs="0"/&gt;
 *         &lt;element name="StatusGroup" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/&gt;
 *         &lt;element ref="{http://www.fleetboard.com/data}VhcStatusLayout" minOccurs="0"/&gt;
 *         &lt;element ref="{http://www.fleetboard.com/data}SemanticsDef" minOccurs="0"/&gt;
 *         &lt;element name="FormDefInoID" type="{http://www.fleetboard.com/data}inoidType" minOccurs="0"/&gt;
 *       &lt;/sequence&gt;
 *       &lt;attribute name="inoid" type="{http://www.fleetboard.com/data}inoidType" /&gt;
 *       &lt;attribute name="fbid" type="{http://www.fleetboard.com/data}fbidType" /&gt;
 *     &lt;/restriction&gt;
 *   &lt;/complexContent&gt;
 * &lt;/complexType&gt;
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "fleetid",
    "type",
    "statusLayout",
    "action",
    "history",
    "visible",
    "showable",
    "statusGroup",
    "vhcStatusLayout",
    "semanticsDef",
    "formDefInoID"
})
@XmlRootElement(name = "StatusDef")
public class StatusDef {

    @XmlElement(name = "FLEETID")
    protected long fleetid;
    @XmlElement(name = "Type", required = true)
    protected StatusDef.Type type;
    @XmlElement(name = "StatusLayout", required = true)
    protected StatusLayout statusLayout;
    @XmlElement(name = "Action", required = true)
    protected Action action;
    @XmlElement(name = "History")
    protected History history;
    @XmlElement(name = "Visible")
    protected String visible;
    @XmlElement(name = "Showable")
    protected BigInteger showable;
    @XmlElement(name = "StatusGroup")
    protected String statusGroup;
    @XmlElement(name = "VhcStatusLayout", nillable = true)
    protected VhcStatusLayout vhcStatusLayout;
    @XmlElement(name = "SemanticsDef")
    protected SemanticsDef semanticsDef;
    @XmlElement(name = "FormDefInoID")
    protected String formDefInoID;
    @XmlAttribute(name = "inoid")
    protected String inoid;
    @XmlAttribute(name = "fbid")
    protected String fbid;

    /**
     * Gets the value of the fleetid property.
     * 
     */
    public long getFLEETID() {
        return fleetid;
    }

    /**
     * Sets the value of the fleetid property.
     * 
     */
    public void setFLEETID(long value) {
        this.fleetid = value;
    }

    /**
     * Gets the value of the type property.
     * 
     * @return
     *     possible object is
     *     {@link StatusDef.Type }
     *     
     */
    public StatusDef.Type getType() {
        return type;
    }

    /**
     * Sets the value of the type property.
     * 
     * @param value
     *     allowed object is
     *     {@link StatusDef.Type }
     *     
     */
    public void setType(StatusDef.Type value) {
        this.type = value;
    }

    /**
     * Gets the value of the statusLayout property.
     * 
     * @return
     *     possible object is
     *     {@link StatusLayout }
     *     
     */
    public StatusLayout getStatusLayout() {
        return statusLayout;
    }

    /**
     * Sets the value of the statusLayout property.
     * 
     * @param value
     *     allowed object is
     *     {@link StatusLayout }
     *     
     */
    public void setStatusLayout(StatusLayout value) {
        this.statusLayout = value;
    }

    /**
     * Gets the value of the action property.
     * 
     * @return
     *     possible object is
     *     {@link Action }
     *     
     */
    public Action getAction() {
        return action;
    }

    /**
     * Sets the value of the action property.
     * 
     * @param value
     *     allowed object is
     *     {@link Action }
     *     
     */
    public void setAction(Action value) {
        this.action = value;
    }

    /**
     * Gets the value of the history property.
     * 
     * @return
     *     possible object is
     *     {@link History }
     *     
     */
    public History getHistory() {
        return history;
    }

    /**
     * Sets the value of the history property.
     * 
     * @param value
     *     allowed object is
     *     {@link History }
     *     
     */
    public void setHistory(History value) {
        this.history = value;
    }

    /**
     * Gets the value of the visible property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getVisible() {
        return visible;
    }

    /**
     * Sets the value of the visible property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setVisible(String value) {
        this.visible = value;
    }

    /**
     * Gets the value of the showable property.
     * 
     * @return
     *     possible object is
     *     {@link BigInteger }
     *     
     */
    public BigInteger getShowable() {
        return showable;
    }

    /**
     * Sets the value of the showable property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigInteger }
     *     
     */
    public void setShowable(BigInteger value) {
        this.showable = value;
    }

    /**
     * Gets the value of the statusGroup property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getStatusGroup() {
        return statusGroup;
    }

    /**
     * Sets the value of the statusGroup property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setStatusGroup(String value) {
        this.statusGroup = value;
    }

    /**
     * Gets the value of the vhcStatusLayout property.
     * 
     * @return
     *     possible object is
     *     {@link VhcStatusLayout }
     *     
     */
    public VhcStatusLayout getVhcStatusLayout() {
        return vhcStatusLayout;
    }

    /**
     * Sets the value of the vhcStatusLayout property.
     * 
     * @param value
     *     allowed object is
     *     {@link VhcStatusLayout }
     *     
     */
    public void setVhcStatusLayout(VhcStatusLayout value) {
        this.vhcStatusLayout = value;
    }

    /**
     * Gets the value of the semanticsDef property.
     * 
     * @return
     *     possible object is
     *     {@link SemanticsDef }
     *     
     */
    public SemanticsDef getSemanticsDef() {
        return semanticsDef;
    }

    /**
     * Sets the value of the semanticsDef property.
     * 
     * @param value
     *     allowed object is
     *     {@link SemanticsDef }
     *     
     */
    public void setSemanticsDef(SemanticsDef value) {
        this.semanticsDef = value;
    }

    /**
     * Gets the value of the formDefInoID property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getFormDefInoID() {
        return formDefInoID;
    }

    /**
     * Sets the value of the formDefInoID property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setFormDefInoID(String value) {
        this.formDefInoID = value;
    }

    /**
     * Gets the value of the inoid property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getInoid() {
        return inoid;
    }

    /**
     * Sets the value of the inoid property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setInoid(String value) {
        this.inoid = value;
    }

    /**
     * Gets the value of the fbid property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getFbid() {
        return fbid;
    }

    /**
     * Sets the value of the fbid property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setFbid(String value) {
        this.fbid = value;
    }


    /**
     * <p>Java class for anonymous complex type.
     * 
     * <p>The following schema fragment specifies the expected content contained within this class.
     * 
     * <pre>
     * &lt;complexType&gt;
     *   &lt;complexContent&gt;
     *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
     *       &lt;sequence&gt;
     *         &lt;element name="Kind" type="{http://www.w3.org/2001/XMLSchema}string"/&gt;
     *         &lt;element name="ATSRegister" type="{http://www.w3.org/2001/XMLSchema}string"/&gt;
     *       &lt;/sequence&gt;
     *     &lt;/restriction&gt;
     *   &lt;/complexContent&gt;
     * &lt;/complexType&gt;
     * </pre>
     * 
     * 
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "", propOrder = {
        "kind",
        "atsRegister"
    })
    public static class Type {

        @XmlElement(name = "Kind", required = true)
        protected String kind;
        @XmlElement(name = "ATSRegister", required = true)
        protected String atsRegister;

        /**
         * Gets the value of the kind property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getKind() {
            return kind;
        }

        /**
         * Sets the value of the kind property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setKind(String value) {
            this.kind = value;
        }

        /**
         * Gets the value of the atsRegister property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getATSRegister() {
            return atsRegister;
        }

        /**
         * Sets the value of the atsRegister property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setATSRegister(String value) {
            this.atsRegister = value;
        }

    }

}
