//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.11 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2017.09.06 at 01:34:55 AM CEST 
//


package pl.oskarpolak.automatic.models.soap.basicservice;

import java.math.BigInteger;
import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for TmSoapUserType complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="TmSoapUserType"&gt;
 *   &lt;complexContent&gt;
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
 *       &lt;sequence&gt;
 *         &lt;element name="ID" type="{http://www.w3.org/2001/XMLSchema}long"/&gt;
 *         &lt;element name="UserSettings" minOccurs="0"&gt;
 *           &lt;complexType&gt;
 *             &lt;complexContent&gt;
 *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
 *                 &lt;sequence&gt;
 *                   &lt;element name="FleetID" type="{http://www.fleetboard.com/data}fleetidType"/&gt;
 *                   &lt;element name="Name" type="{http://www.w3.org/2001/XMLSchema}string"/&gt;
 *                   &lt;element name="Description" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/&gt;
 *                   &lt;element name="Locale" type="{http://www.w3.org/2001/XMLSchema}string"/&gt;
 *                   &lt;element name="Login" type="{http://www.w3.org/2001/XMLSchema}string"/&gt;
 *                   &lt;element name="Status" type="{http://www.w3.org/2001/XMLSchema}integer" minOccurs="0"/&gt;
 *                   &lt;element name="UserGroup" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/&gt;
 *                   &lt;element name="ProfileId" type="{http://www.fleetboard.com/data}idType" minOccurs="0"/&gt;
 *                   &lt;element name="EndDate" type="{http://www.fleetboard.com/data}timestampType" minOccurs="0"/&gt;
 *                   &lt;element name="MobilePhone" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/&gt;
 *                   &lt;element name="Email" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/&gt;
 *                   &lt;element name="CSVSeparator" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/&gt;
 *                   &lt;element name="LastAmended" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/&gt;
 *                   &lt;element name="AmendedBy" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/&gt;
 *                 &lt;/sequence&gt;
 *               &lt;/restriction&gt;
 *             &lt;/complexContent&gt;
 *           &lt;/complexType&gt;
 *         &lt;/element&gt;
 *         &lt;element name="RightSettings" minOccurs="0"&gt;
 *           &lt;complexType&gt;
 *             &lt;complexContent&gt;
 *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
 *                 &lt;sequence&gt;
 *                   &lt;element name="Right" type="{http://www.w3.org/2001/XMLSchema}string" maxOccurs="unbounded" minOccurs="0"/&gt;
 *                 &lt;/sequence&gt;
 *               &lt;/restriction&gt;
 *             &lt;/complexContent&gt;
 *           &lt;/complexType&gt;
 *         &lt;/element&gt;
 *       &lt;/sequence&gt;
 *     &lt;/restriction&gt;
 *   &lt;/complexContent&gt;
 * &lt;/complexType&gt;
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "TmSoapUserType", propOrder = {
    "id",
    "userSettings",
    "rightSettings"
})
public class TmSoapUserType {

    @XmlElement(name = "ID")
    protected long id;
    @XmlElement(name = "UserSettings")
    protected TmSoapUserType.UserSettings userSettings;
    @XmlElement(name = "RightSettings")
    protected TmSoapUserType.RightSettings rightSettings;

    /**
     * Gets the value of the id property.
     * 
     */
    public long getID() {
        return id;
    }

    /**
     * Sets the value of the id property.
     * 
     */
    public void setID(long value) {
        this.id = value;
    }

    /**
     * Gets the value of the userSettings property.
     * 
     * @return
     *     possible object is
     *     {@link TmSoapUserType.UserSettings }
     *     
     */
    public TmSoapUserType.UserSettings getUserSettings() {
        return userSettings;
    }

    /**
     * Sets the value of the userSettings property.
     * 
     * @param value
     *     allowed object is
     *     {@link TmSoapUserType.UserSettings }
     *     
     */
    public void setUserSettings(TmSoapUserType.UserSettings value) {
        this.userSettings = value;
    }

    /**
     * Gets the value of the rightSettings property.
     * 
     * @return
     *     possible object is
     *     {@link TmSoapUserType.RightSettings }
     *     
     */
    public TmSoapUserType.RightSettings getRightSettings() {
        return rightSettings;
    }

    /**
     * Sets the value of the rightSettings property.
     * 
     * @param value
     *     allowed object is
     *     {@link TmSoapUserType.RightSettings }
     *     
     */
    public void setRightSettings(TmSoapUserType.RightSettings value) {
        this.rightSettings = value;
    }


    /**
     * <p>Java class for anonymous complex type.
     * 
     * <p>The following schema fragment specifies the expected content contained within this class.
     * 
     * <pre>
     * &lt;complexType&gt;
     *   &lt;complexContent&gt;
     *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
     *       &lt;sequence&gt;
     *         &lt;element name="Right" type="{http://www.w3.org/2001/XMLSchema}string" maxOccurs="unbounded" minOccurs="0"/&gt;
     *       &lt;/sequence&gt;
     *     &lt;/restriction&gt;
     *   &lt;/complexContent&gt;
     * &lt;/complexType&gt;
     * </pre>
     * 
     * 
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "", propOrder = {
        "right"
    })
    public static class RightSettings {

        @XmlElement(name = "Right")
        protected List<String> right;

        /**
         * Gets the value of the right property.
         * 
         * <p>
         * This accessor method returns a reference to the live list,
         * not a snapshot. Therefore any modification you make to the
         * returned list will be present inside the JAXB object.
         * This is why there is not a <CODE>set</CODE> method for the right property.
         * 
         * <p>
         * For example, to add a new item, do as follows:
         * <pre>
         *    getRight().add(newItem);
         * </pre>
         * 
         * 
         * <p>
         * Objects of the following type(s) are allowed in the list
         * {@link String }
         * 
         * 
         */
        public List<String> getRight() {
            if (right == null) {
                right = new ArrayList<String>();
            }
            return this.right;
        }

    }


    /**
     * <p>Java class for anonymous complex type.
     * 
     * <p>The following schema fragment specifies the expected content contained within this class.
     * 
     * <pre>
     * &lt;complexType&gt;
     *   &lt;complexContent&gt;
     *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
     *       &lt;sequence&gt;
     *         &lt;element name="FleetID" type="{http://www.fleetboard.com/data}fleetidType"/&gt;
     *         &lt;element name="Name" type="{http://www.w3.org/2001/XMLSchema}string"/&gt;
     *         &lt;element name="Description" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/&gt;
     *         &lt;element name="Locale" type="{http://www.w3.org/2001/XMLSchema}string"/&gt;
     *         &lt;element name="Login" type="{http://www.w3.org/2001/XMLSchema}string"/&gt;
     *         &lt;element name="Status" type="{http://www.w3.org/2001/XMLSchema}integer" minOccurs="0"/&gt;
     *         &lt;element name="UserGroup" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/&gt;
     *         &lt;element name="ProfileId" type="{http://www.fleetboard.com/data}idType" minOccurs="0"/&gt;
     *         &lt;element name="EndDate" type="{http://www.fleetboard.com/data}timestampType" minOccurs="0"/&gt;
     *         &lt;element name="MobilePhone" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/&gt;
     *         &lt;element name="Email" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/&gt;
     *         &lt;element name="CSVSeparator" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/&gt;
     *         &lt;element name="LastAmended" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/&gt;
     *         &lt;element name="AmendedBy" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/&gt;
     *       &lt;/sequence&gt;
     *     &lt;/restriction&gt;
     *   &lt;/complexContent&gt;
     * &lt;/complexType&gt;
     * </pre>
     * 
     * 
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "", propOrder = {
        "fleetID",
        "name",
        "description",
        "locale",
        "login",
        "status",
        "userGroup",
        "profileId",
        "endDate",
        "mobilePhone",
        "email",
        "csvSeparator",
        "lastAmended",
        "amendedBy"
    })
    public static class UserSettings {

        @XmlElement(name = "FleetID")
        protected long fleetID;
        @XmlElement(name = "Name", required = true)
        protected String name;
        @XmlElement(name = "Description")
        protected String description;
        @XmlElement(name = "Locale", required = true)
        protected String locale;
        @XmlElement(name = "Login", required = true)
        protected String login;
        @XmlElement(name = "Status")
        protected BigInteger status;
        @XmlElement(name = "UserGroup")
        protected String userGroup;
        @XmlElement(name = "ProfileId")
        protected Long profileId;
        @XmlElement(name = "EndDate")
        protected String endDate;
        @XmlElement(name = "MobilePhone")
        protected String mobilePhone;
        @XmlElement(name = "Email")
        protected String email;
        @XmlElement(name = "CSVSeparator")
        protected String csvSeparator;
        @XmlElement(name = "LastAmended")
        protected String lastAmended;
        @XmlElement(name = "AmendedBy")
        protected String amendedBy;

        /**
         * Gets the value of the fleetID property.
         * 
         */
        public long getFleetID() {
            return fleetID;
        }

        /**
         * Sets the value of the fleetID property.
         * 
         */
        public void setFleetID(long value) {
            this.fleetID = value;
        }

        /**
         * Gets the value of the name property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getName() {
            return name;
        }

        /**
         * Sets the value of the name property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setName(String value) {
            this.name = value;
        }

        /**
         * Gets the value of the description property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getDescription() {
            return description;
        }

        /**
         * Sets the value of the description property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setDescription(String value) {
            this.description = value;
        }

        /**
         * Gets the value of the locale property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getLocale() {
            return locale;
        }

        /**
         * Sets the value of the locale property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setLocale(String value) {
            this.locale = value;
        }

        /**
         * Gets the value of the login property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getLogin() {
            return login;
        }

        /**
         * Sets the value of the login property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setLogin(String value) {
            this.login = value;
        }

        /**
         * Gets the value of the status property.
         * 
         * @return
         *     possible object is
         *     {@link BigInteger }
         *     
         */
        public BigInteger getStatus() {
            return status;
        }

        /**
         * Sets the value of the status property.
         * 
         * @param value
         *     allowed object is
         *     {@link BigInteger }
         *     
         */
        public void setStatus(BigInteger value) {
            this.status = value;
        }

        /**
         * Gets the value of the userGroup property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getUserGroup() {
            return userGroup;
        }

        /**
         * Sets the value of the userGroup property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setUserGroup(String value) {
            this.userGroup = value;
        }

        /**
         * Gets the value of the profileId property.
         * 
         * @return
         *     possible object is
         *     {@link Long }
         *     
         */
        public Long getProfileId() {
            return profileId;
        }

        /**
         * Sets the value of the profileId property.
         * 
         * @param value
         *     allowed object is
         *     {@link Long }
         *     
         */
        public void setProfileId(Long value) {
            this.profileId = value;
        }

        /**
         * Gets the value of the endDate property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getEndDate() {
            return endDate;
        }

        /**
         * Sets the value of the endDate property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setEndDate(String value) {
            this.endDate = value;
        }

        /**
         * Gets the value of the mobilePhone property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getMobilePhone() {
            return mobilePhone;
        }

        /**
         * Sets the value of the mobilePhone property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setMobilePhone(String value) {
            this.mobilePhone = value;
        }

        /**
         * Gets the value of the email property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getEmail() {
            return email;
        }

        /**
         * Sets the value of the email property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setEmail(String value) {
            this.email = value;
        }

        /**
         * Gets the value of the csvSeparator property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getCSVSeparator() {
            return csvSeparator;
        }

        /**
         * Sets the value of the csvSeparator property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setCSVSeparator(String value) {
            this.csvSeparator = value;
        }

        /**
         * Gets the value of the lastAmended property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getLastAmended() {
            return lastAmended;
        }

        /**
         * Sets the value of the lastAmended property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setLastAmended(String value) {
            this.lastAmended = value;
        }

        /**
         * Gets the value of the amendedBy property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getAmendedBy() {
            return amendedBy;
        }

        /**
         * Sets the value of the amendedBy property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setAmendedBy(String value) {
            this.amendedBy = value;
        }

    }

}
