//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.11 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2017.09.06 at 01:34:55 AM CEST 
//


package pl.oskarpolak.automatic.models.soap.basicservice;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for anonymous complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType&gt;
 *   &lt;complexContent&gt;
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
 *       &lt;sequence&gt;
 *         &lt;element name="ReceiveRQ" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/&gt;
 *         &lt;element name="ReadRQ" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/&gt;
 *       &lt;/sequence&gt;
 *     &lt;/restriction&gt;
 *   &lt;/complexContent&gt;
 * &lt;/complexType&gt;
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "receiveRQ",
    "readRQ"
})
@XmlRootElement(name = "TXMessage")
public class TXMessage {

    @XmlElement(name = "ReceiveRQ")
    protected String receiveRQ;
    @XmlElement(name = "ReadRQ")
    protected String readRQ;

    /**
     * Gets the value of the receiveRQ property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getReceiveRQ() {
        return receiveRQ;
    }

    /**
     * Sets the value of the receiveRQ property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setReceiveRQ(String value) {
        this.receiveRQ = value;
    }

    /**
     * Gets the value of the readRQ property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getReadRQ() {
        return readRQ;
    }

    /**
     * Sets the value of the readRQ property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setReadRQ(String value) {
        this.readRQ = value;
    }

}
