//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.11 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2017.09.06 at 01:34:55 AM CEST 
//


package pl.oskarpolak.automatic.models.soap.basicservice;

import java.math.BigInteger;
import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlSchemaType;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for anonymous complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType&gt;
 *   &lt;complexContent&gt;
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
 *       &lt;sequence&gt;
 *         &lt;element name="CHASSIS" type="{http://www.w3.org/2001/XMLSchema}string"/&gt;
 *         &lt;element name="VEHICLEHARDWARE" maxOccurs="unbounded" minOccurs="0"&gt;
 *           &lt;complexType&gt;
 *             &lt;complexContent&gt;
 *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
 *                 &lt;sequence&gt;
 *                   &lt;element name="HARDWARE" type="{http://www.w3.org/2001/XMLSchema}string"/&gt;
 *                   &lt;element name="HARDWAREID" type="{http://www.w3.org/2001/XMLSchema}integer"/&gt;
 *                 &lt;/sequence&gt;
 *               &lt;/restriction&gt;
 *             &lt;/complexContent&gt;
 *           &lt;/complexType&gt;
 *         &lt;/element&gt;
 *         &lt;element name="FLEETVEHICLE"&gt;
 *           &lt;complexType&gt;
 *             &lt;complexContent&gt;
 *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
 *                 &lt;sequence&gt;
 *                   &lt;element name="FLEETID" type="{http://www.fleetboard.com/data}fleetidType"/&gt;
 *                   &lt;element name="REGISTRATION" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/&gt;
 *                   &lt;element name="VEHICLENUMBER" type="{http://www.w3.org/2001/XMLSchema}string"/&gt;
 *                   &lt;element name="INSMSISDN" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/&gt;
 *                   &lt;element name="STARTTIME" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/&gt;
 *                   &lt;element name="ENDTIME" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/&gt;
 *                   &lt;element name="VEHICLETYPE" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/&gt;
 *                   &lt;element name="STATUS" type="{http://www.w3.org/2001/XMLSchema}integer" minOccurs="0"/&gt;
 *                 &lt;/sequence&gt;
 *               &lt;/restriction&gt;
 *             &lt;/complexContent&gt;
 *           &lt;/complexType&gt;
 *         &lt;/element&gt;
 *         &lt;element name="GROUPVEHICLE" minOccurs="0"&gt;
 *           &lt;complexType&gt;
 *             &lt;complexContent&gt;
 *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
 *                 &lt;sequence&gt;
 *                   &lt;element name="GROUPID" type="{http://www.w3.org/2001/XMLSchema}string" maxOccurs="unbounded" minOccurs="0"/&gt;
 *                 &lt;/sequence&gt;
 *               &lt;/restriction&gt;
 *             &lt;/complexContent&gt;
 *           &lt;/complexType&gt;
 *         &lt;/element&gt;
 *         &lt;element name="REGISTRATIONDATE" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/&gt;
 *         &lt;element name="TELEMATICGROUP" type="{http://www.fleetboard.com/data}telematicGroupIDType" minOccurs="0"/&gt;
 *         &lt;element name="VEHICLEPROPERTIES" minOccurs="0"&gt;
 *           &lt;complexType&gt;
 *             &lt;complexContent&gt;
 *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
 *                 &lt;sequence&gt;
 *                   &lt;element name="Property" type="{http://www.fleetboard.com/data}PropertyType" maxOccurs="unbounded" minOccurs="0"/&gt;
 *                 &lt;/sequence&gt;
 *               &lt;/restriction&gt;
 *             &lt;/complexContent&gt;
 *           &lt;/complexType&gt;
 *         &lt;/element&gt;
 *       &lt;/sequence&gt;
 *       &lt;attribute name="inoid" use="required" type="{http://www.fleetboard.com/data}inoidType" /&gt;
 *     &lt;/restriction&gt;
 *   &lt;/complexContent&gt;
 * &lt;/complexType&gt;
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "chassis",
    "vehiclehardware",
    "fleetvehicle",
    "groupvehicle",
    "registrationdate",
    "telematicgroup",
    "vehicleproperties"
})
@XmlRootElement(name = "VEHICLE")
public class VEHICLE {

    @XmlElement(name = "CHASSIS", required = true)
    protected String chassis;
    @XmlElement(name = "VEHICLEHARDWARE")
    protected List<VEHICLE.VEHICLEHARDWARE> vehiclehardware;
    @XmlElement(name = "FLEETVEHICLE", required = true)
    protected VEHICLE.FLEETVEHICLE fleetvehicle;
    @XmlElement(name = "GROUPVEHICLE")
    protected VEHICLE.GROUPVEHICLE groupvehicle;
    @XmlElement(name = "REGISTRATIONDATE")
    protected String registrationdate;
    @XmlElement(name = "TELEMATICGROUP")
    @XmlSchemaType(name = "string")
    protected TelematicGroupIDType telematicgroup;
    @XmlElement(name = "VEHICLEPROPERTIES")
    protected VEHICLE.VEHICLEPROPERTIES vehicleproperties;
    @XmlAttribute(name = "inoid", required = true)
    protected String inoid;

    /**
     * Gets the value of the chassis property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getCHASSIS() {
        return chassis;
    }

    /**
     * Sets the value of the chassis property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setCHASSIS(String value) {
        this.chassis = value;
    }

    /**
     * Gets the value of the vehiclehardware property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the vehiclehardware property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getVEHICLEHARDWARE().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link VEHICLE.VEHICLEHARDWARE }
     * 
     * 
     */
    public List<VEHICLE.VEHICLEHARDWARE> getVEHICLEHARDWARE() {
        if (vehiclehardware == null) {
            vehiclehardware = new ArrayList<VEHICLE.VEHICLEHARDWARE>();
        }
        return this.vehiclehardware;
    }

    /**
     * Gets the value of the fleetvehicle property.
     * 
     * @return
     *     possible object is
     *     {@link VEHICLE.FLEETVEHICLE }
     *     
     */
    public VEHICLE.FLEETVEHICLE getFLEETVEHICLE() {
        return fleetvehicle;
    }

    /**
     * Sets the value of the fleetvehicle property.
     * 
     * @param value
     *     allowed object is
     *     {@link VEHICLE.FLEETVEHICLE }
     *     
     */
    public void setFLEETVEHICLE(VEHICLE.FLEETVEHICLE value) {
        this.fleetvehicle = value;
    }

    /**
     * Gets the value of the groupvehicle property.
     * 
     * @return
     *     possible object is
     *     {@link VEHICLE.GROUPVEHICLE }
     *     
     */
    public VEHICLE.GROUPVEHICLE getGROUPVEHICLE() {
        return groupvehicle;
    }

    /**
     * Sets the value of the groupvehicle property.
     * 
     * @param value
     *     allowed object is
     *     {@link VEHICLE.GROUPVEHICLE }
     *     
     */
    public void setGROUPVEHICLE(VEHICLE.GROUPVEHICLE value) {
        this.groupvehicle = value;
    }

    /**
     * Gets the value of the registrationdate property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getREGISTRATIONDATE() {
        return registrationdate;
    }

    /**
     * Sets the value of the registrationdate property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setREGISTRATIONDATE(String value) {
        this.registrationdate = value;
    }

    /**
     * Gets the value of the telematicgroup property.
     * 
     * @return
     *     possible object is
     *     {@link TelematicGroupIDType }
     *     
     */
    public TelematicGroupIDType getTELEMATICGROUP() {
        return telematicgroup;
    }

    /**
     * Sets the value of the telematicgroup property.
     * 
     * @param value
     *     allowed object is
     *     {@link TelematicGroupIDType }
     *     
     */
    public void setTELEMATICGROUP(TelematicGroupIDType value) {
        this.telematicgroup = value;
    }

    /**
     * Gets the value of the vehicleproperties property.
     * 
     * @return
     *     possible object is
     *     {@link VEHICLE.VEHICLEPROPERTIES }
     *     
     */
    public VEHICLE.VEHICLEPROPERTIES getVEHICLEPROPERTIES() {
        return vehicleproperties;
    }

    /**
     * Sets the value of the vehicleproperties property.
     * 
     * @param value
     *     allowed object is
     *     {@link VEHICLE.VEHICLEPROPERTIES }
     *     
     */
    public void setVEHICLEPROPERTIES(VEHICLE.VEHICLEPROPERTIES value) {
        this.vehicleproperties = value;
    }

    /**
     * Gets the value of the inoid property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getInoid() {
        return inoid;
    }

    /**
     * Sets the value of the inoid property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setInoid(String value) {
        this.inoid = value;
    }


    /**
     * <p>Java class for anonymous complex type.
     * 
     * <p>The following schema fragment specifies the expected content contained within this class.
     * 
     * <pre>
     * &lt;complexType&gt;
     *   &lt;complexContent&gt;
     *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
     *       &lt;sequence&gt;
     *         &lt;element name="FLEETID" type="{http://www.fleetboard.com/data}fleetidType"/&gt;
     *         &lt;element name="REGISTRATION" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/&gt;
     *         &lt;element name="VEHICLENUMBER" type="{http://www.w3.org/2001/XMLSchema}string"/&gt;
     *         &lt;element name="INSMSISDN" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/&gt;
     *         &lt;element name="STARTTIME" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/&gt;
     *         &lt;element name="ENDTIME" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/&gt;
     *         &lt;element name="VEHICLETYPE" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/&gt;
     *         &lt;element name="STATUS" type="{http://www.w3.org/2001/XMLSchema}integer" minOccurs="0"/&gt;
     *       &lt;/sequence&gt;
     *     &lt;/restriction&gt;
     *   &lt;/complexContent&gt;
     * &lt;/complexType&gt;
     * </pre>
     * 
     * 
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "", propOrder = {
        "fleetid",
        "registration",
        "vehiclenumber",
        "insmsisdn",
        "starttime",
        "endtime",
        "vehicletype",
        "status"
    })
    public static class FLEETVEHICLE {

        @XmlElement(name = "FLEETID")
        protected long fleetid;
        @XmlElement(name = "REGISTRATION")
        protected String registration;
        @XmlElement(name = "VEHICLENUMBER", required = true)
        protected String vehiclenumber;
        @XmlElement(name = "INSMSISDN")
        protected String insmsisdn;
        @XmlElement(name = "STARTTIME")
        protected String starttime;
        @XmlElement(name = "ENDTIME")
        protected String endtime;
        @XmlElement(name = "VEHICLETYPE")
        protected String vehicletype;
        @XmlElement(name = "STATUS")
        protected BigInteger status;

        /**
         * Gets the value of the fleetid property.
         * 
         */
        public long getFLEETID() {
            return fleetid;
        }

        /**
         * Sets the value of the fleetid property.
         * 
         */
        public void setFLEETID(long value) {
            this.fleetid = value;
        }

        /**
         * Gets the value of the registration property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getREGISTRATION() {
            return registration;
        }

        /**
         * Sets the value of the registration property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setREGISTRATION(String value) {
            this.registration = value;
        }

        /**
         * Gets the value of the vehiclenumber property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getVEHICLENUMBER() {
            return vehiclenumber;
        }

        /**
         * Sets the value of the vehiclenumber property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setVEHICLENUMBER(String value) {
            this.vehiclenumber = value;
        }

        /**
         * Gets the value of the insmsisdn property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getINSMSISDN() {
            return insmsisdn;
        }

        /**
         * Sets the value of the insmsisdn property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setINSMSISDN(String value) {
            this.insmsisdn = value;
        }

        /**
         * Gets the value of the starttime property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getSTARTTIME() {
            return starttime;
        }

        /**
         * Sets the value of the starttime property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setSTARTTIME(String value) {
            this.starttime = value;
        }

        /**
         * Gets the value of the endtime property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getENDTIME() {
            return endtime;
        }

        /**
         * Sets the value of the endtime property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setENDTIME(String value) {
            this.endtime = value;
        }

        /**
         * Gets the value of the vehicletype property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getVEHICLETYPE() {
            return vehicletype;
        }

        /**
         * Sets the value of the vehicletype property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setVEHICLETYPE(String value) {
            this.vehicletype = value;
        }

        /**
         * Gets the value of the status property.
         * 
         * @return
         *     possible object is
         *     {@link BigInteger }
         *     
         */
        public BigInteger getSTATUS() {
            return status;
        }

        /**
         * Sets the value of the status property.
         * 
         * @param value
         *     allowed object is
         *     {@link BigInteger }
         *     
         */
        public void setSTATUS(BigInteger value) {
            this.status = value;
        }

    }


    /**
     * <p>Java class for anonymous complex type.
     * 
     * <p>The following schema fragment specifies the expected content contained within this class.
     * 
     * <pre>
     * &lt;complexType&gt;
     *   &lt;complexContent&gt;
     *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
     *       &lt;sequence&gt;
     *         &lt;element name="GROUPID" type="{http://www.w3.org/2001/XMLSchema}string" maxOccurs="unbounded" minOccurs="0"/&gt;
     *       &lt;/sequence&gt;
     *     &lt;/restriction&gt;
     *   &lt;/complexContent&gt;
     * &lt;/complexType&gt;
     * </pre>
     * 
     * 
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "", propOrder = {
        "groupid"
    })
    public static class GROUPVEHICLE {

        @XmlElement(name = "GROUPID")
        protected List<String> groupid;

        /**
         * Gets the value of the groupid property.
         * 
         * <p>
         * This accessor method returns a reference to the live list,
         * not a snapshot. Therefore any modification you make to the
         * returned list will be present inside the JAXB object.
         * This is why there is not a <CODE>set</CODE> method for the groupid property.
         * 
         * <p>
         * For example, to add a new item, do as follows:
         * <pre>
         *    getGROUPID().add(newItem);
         * </pre>
         * 
         * 
         * <p>
         * Objects of the following type(s) are allowed in the list
         * {@link String }
         * 
         * 
         */
        public List<String> getGROUPID() {
            if (groupid == null) {
                groupid = new ArrayList<String>();
            }
            return this.groupid;
        }

    }


    /**
     * <p>Java class for anonymous complex type.
     * 
     * <p>The following schema fragment specifies the expected content contained within this class.
     * 
     * <pre>
     * &lt;complexType&gt;
     *   &lt;complexContent&gt;
     *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
     *       &lt;sequence&gt;
     *         &lt;element name="HARDWARE" type="{http://www.w3.org/2001/XMLSchema}string"/&gt;
     *         &lt;element name="HARDWAREID" type="{http://www.w3.org/2001/XMLSchema}integer"/&gt;
     *       &lt;/sequence&gt;
     *     &lt;/restriction&gt;
     *   &lt;/complexContent&gt;
     * &lt;/complexType&gt;
     * </pre>
     * 
     * 
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "", propOrder = {
        "hardware",
        "hardwareid"
    })
    public static class VEHICLEHARDWARE {

        @XmlElement(name = "HARDWARE", required = true)
        protected String hardware;
        @XmlElement(name = "HARDWAREID", required = true)
        protected BigInteger hardwareid;

        /**
         * Gets the value of the hardware property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getHARDWARE() {
            return hardware;
        }

        /**
         * Sets the value of the hardware property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setHARDWARE(String value) {
            this.hardware = value;
        }

        /**
         * Gets the value of the hardwareid property.
         * 
         * @return
         *     possible object is
         *     {@link BigInteger }
         *     
         */
        public BigInteger getHARDWAREID() {
            return hardwareid;
        }

        /**
         * Sets the value of the hardwareid property.
         * 
         * @param value
         *     allowed object is
         *     {@link BigInteger }
         *     
         */
        public void setHARDWAREID(BigInteger value) {
            this.hardwareid = value;
        }

    }


    /**
     * <p>Java class for anonymous complex type.
     * 
     * <p>The following schema fragment specifies the expected content contained within this class.
     * 
     * <pre>
     * &lt;complexType&gt;
     *   &lt;complexContent&gt;
     *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
     *       &lt;sequence&gt;
     *         &lt;element name="Property" type="{http://www.fleetboard.com/data}PropertyType" maxOccurs="unbounded" minOccurs="0"/&gt;
     *       &lt;/sequence&gt;
     *     &lt;/restriction&gt;
     *   &lt;/complexContent&gt;
     * &lt;/complexType&gt;
     * </pre>
     * 
     * 
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "", propOrder = {
        "property"
    })
    public static class VEHICLEPROPERTIES {

        @XmlElement(name = "Property")
        protected List<PropertyType> property;

        /**
         * Gets the value of the property property.
         * 
         * <p>
         * This accessor method returns a reference to the live list,
         * not a snapshot. Therefore any modification you make to the
         * returned list will be present inside the JAXB object.
         * This is why there is not a <CODE>set</CODE> method for the property property.
         * 
         * <p>
         * For example, to add a new item, do as follows:
         * <pre>
         *    getProperty().add(newItem);
         * </pre>
         * 
         * 
         * <p>
         * Objects of the following type(s) are allowed in the list
         * {@link PropertyType }
         * 
         * 
         */
        public List<PropertyType> getProperty() {
            if (property == null) {
                property = new ArrayList<PropertyType>();
            }
            return this.property;
        }

    }

}
